description: Best hyperparameters from HPO trials (from NeuralNetTorch\T11)
eval_metric: average_precision
problem_type: binary
hyperparameters:
  NeuralNetTorch\T11: {}
training_config:
  time_limit: 3600
  presets: null
  use_bag_holdout: true
